# language: github actions

name: build our image

on:
  push:
    branches: master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: build the image
        run: |
          docker buildx build \
            --tag thomo/dnsbind9:1.0.3 \
            --tag thomo/dnsbind9:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
