# language: github actions

name: build our image

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Read version from properties file
        id: read_property
        uses: Reedyuk/read-properties@v1.0.4
        with:
          path: 'build.properties'
          property: 'version'

      - name: build the image
        run: |
          docker buildx build --push \
            --tag thomo/dnsbind9:${{ steps.read_property.outputs.value }} \
            --tag thomo/dnsbind9:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm/v8,linux/arm64 .
